// APP
export var APP_LOAD_REQUEST = 'APP_LOAD_REQUEST';
export var APP_LOAD_SUCCESS = 'APP_LOAD_SUCCESS';
// ERRORS
export var ERROR = 'ERROR';
export var AWK_ERROR = 'AWK_ERROR';
// UI
export var LOADING = 'LOADING';
// AUTH
export var LOGIN_REQUEST = 'LOGIN_REQUEST';
export var LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export var CURRENT_USER_REQUEST = 'CURRENT_USER_REQUEST';
export var CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS';
// HISTORY
export var HISTORY_PUSH_REQUEST = 'HISTORY_PUSH_REQUEST';
export var HISTORY_PUSH_SUCCESS = 'HISTORY_PUSH_SUCCESS';
